import React, {useContext} from 'react';
import {GadgetsContext} from '../context/GadgetsContext';

const useGadgets = () => {
  const {
    gadgetsLoading,
    setGadgetsLoading,
    allGadgets,
    setAllGadgets,
    groundLight,
    setGroundLight,
    level1Light,
    setLevel1Light,
    door,
    setDoor,
    powerSocket,
    setPowerSocket,
    allLights,
    setAllLights,
    ws,
    groundLoading,
    setGroundLoading,
    level1Loading,
    setLevel1Loading,
    doorLoading,
    setDoorLoading,
    powerLoading,
    setPowerLoading,
    allLoading,
    setAllLoading,
    refresh,
    setRefresh,
    refreshing,
    setRefreshing,
  } = useContext(GadgetsContext);
  return {
    gadgetsLoading,
    setGadgetsLoading,
    allGadgets,
    setAllGadgets,
    groundLight,
    setGroundLight,
    level1Light,
    setLevel1Light,
    door,
    setDoor,
    powerSocket,
    setPowerSocket,
    allLights,
    setAllLights,
    ws,
    groundLoading,
    setGroundLoading,
    level1Loading,
    setLevel1Loading,
    doorLoading,
    setDoorLoading,
    powerLoading,
    setPowerLoading,
    allLoading,
    setAllLoading,
    refresh,
    setRefresh,
    refreshing,
    setRefreshing,
  };
};

export default useGadgets;
